version: '3.4'

services:
  kubereactesriapp:
    image: kubereactesriapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
